name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Dies ist der Branch, auf den die Action reagiert.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Verwendung von Ubuntu als Betriebssystem

    steps:
      # Schritt 1: Checkout des Codes
      - name: Checkout code
        uses: actions/checkout@v2

      # Schritt 2: Setze Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Gib hier die Node.js-Version an, die du verwenden möchtest

      # Schritt 3: Installiere Abhängigkeiten
      - name: Install dependencies
        run: npm install
        working-directory: ./pawship  # Stelle sicher, dass du den richtigen Ordner angibst, in dem package.json liegt

      # Schritt 4: Baue das Projekt
      - name: Build project
        run: npm run build
        working-directory: ./pawship  # Der Ordner, der die `package.json` und das Projekt enthält

      # Schritt 5: Installiere gh-pages (falls noch nicht installiert)
      - name: Install gh-pages
        run: npm install --save gh-pages
        working-directory: ./pawship  # Der Ordner, der die `package.json` enthält

      # Schritt 6: Konfiguriere Git mit deinem Benutzernamen und deiner E-Mail
      - name: Configure Git
        run: |
          git config --global user.name "gernotfasching"
          git config --global user.email "gernotfasch@gmail.com"

      # Schritt 7: Deploy zu GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./pawship  # Der Ordner, der das Projekt enthält
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token wird verwendet, um auf GitHub Pages zu deployen
